name: Build_DocsSite

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/Build_DocsSite.yml

jobs:

  DeployDocs:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    # Grant the minimum permissions necessary for this job to publish to GitHub Pages
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Using caches in a larger project can really speed up builds
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-mkdocs
          path: .cache

      - name: Cache PowerShell modules
        uses: actions/cache@v4
        with:
          path: ~/.local/share/powershell/Modules
          key: ${{ runner.os }}-psmodules-${{ hashFiles('requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-psmodules-

      - name: Setup PowerShell
        uses: bjompen/UpdatePWSHAction@v1.0.1
        with:
          FixedVersion: '7.3.12'

      - name: Install dependencies
        run: |
          Install-Module -Name PSDepend -Scope CurrentUser -Force
          Import-Module -Name PSDepend
          Invoke-PSDepend -Path './requirements.psd1' -Install -Force
        shell: pwsh

      - name: MkDocs GH-Deploy
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: ./build.ps1 -Bootstrap -Task PublishDocs
